apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/emmauopeople/1community-app-backend
    newTag: sha-ec072d99065eb03d4299aeec2e81f3769d7ea76b
