apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/emmauopeople/1community-app-frontend
    newTag: sha-e5e17d7c524addbb79348291ad263d36d1cafd15
